### ISSUE TITLE
Implement Portfolio Section

### ISSUE THREAD

**Issue by hrafnkellbaldurs** [hrafnkellbaldurs/hrafnkellbaldurs-netlify#14]
Create a portfolio section that has a grid of cards/items that each represent a single project.

### Section structure
- PortfolioSection
  - Items filtered by itemType (f.ex 'development')
    - PortfolioItemGrid 
  - Items filtered by itemType (f.ex 'graphic-design')
    - PortfolioItemGrid

### Section filter
It'd be great to add a filter to be able to filter by technologies #15 

### Setup
- [x] Create Portfolio Section with working waypoint
- [x] Set up basic CSS grid layout for items
- [x] Move Section ids to a constant object

### TODO
- [x] Move code from old site to this one
- [x] Create data for development portfolio items (data/showcases/type='development')
  - [x] Data for already working hosted projects (codepen, github)
- [x] Create data for graphic design portfolio items (data/showcases/type='graphicdesign')
  - [x] Data for already produced images/assets
- [x]  Implement the Section structure described above
