### ISSUE TITLE
Add a Modal component

### ISSUE THREAD

**Issue by hrafnkellbaldurs** [hrafnkellbaldurs/hrafnkellbaldurs-netlify#31]
**Is your feature request related to a problem? Please describe.**
I need to be able to show things in more detail in a dialog

**Describe the solution you'd like**
Find a component to do this. F.ex:
https://github.com/TiuSh/react-simple-modal-slideshow

Or

Context api: https://medium.com/@BogdanSoare/how-to-use-reacts-new-context-api-to-easily-manage-modals-2ae45c7def81
Context implementation for app: https://medium.freecodecamp.org/replacing-redux-with-the-new-react-context-api-8f5d01a00e8c
https://www.npmjs.com/package/react-modal-construction-kit

## Dialog API I chose
http://reactcommunity.org/react-modal/
https://www.npmjs.com/package/react-modal
I chose react-modal because it was the first one I tried that worked the way I wanted it to and did minimal preconfigured styling

**Considerations**
Implement state management first? #56 
Might want to see if it works with a single item

## TODO
- [x] Add open/close actions
- [x] Add dialog state
- [x] Add react-modal
- [x] Create Dialog component with minimal functionality
- [x] Create a default type, where we could add more types later
- [x] Test out actions on SkillBadge and ShowCaseItem
- [x] Add dialog types SKILL, SHOWCASE
- [x] Add SkillModal
  - [x] Add SkillModalContainer
- [x] Add ShowcaseModal
  - [x] Add ShowcaseModalContainer
- [x] Remove modal.renderContent from state
- [x] Has title as a parameter
- [x] Create small, medium and large size variants
  - [x] small
    - [x] max-width: 200px;
     - [x] min-width: 100px;
    - [x] min-height: 100px;
  - [x] medium
    - [x] max-width: 400px;
    - [x] min-width: 200px;
    - [x] min-height: 300px;
  - [x] large
    - [x] max-width: 100% (padding: 30px);
    - [x] min-width: 400px;
    - [x] min-height: 500px
- [x] Style dialog container so that it looks nice and has x button to close
  - [x] is centered
  - [x] has x button to close (low priority)
  - [x] has open/close transition animation (low priority)
  - [x] is scrollable
    - [x] if scrollable, start at top of dialog, f.ex for small screens (low priority)
  - [x] locks page scroll
  - [x] is responsive (has at least padding)
