### ISSUE TITLE
Create dialog for SkillBadge onclick

### ISSUE THREAD

**Issue by hrafnkellbaldurs** [hrafnkellbaldurs/hrafnkellbaldurs-netlify#50]
Related to #8 
Needs #31 to be done to be able to start development

## TODO
- [x] Uses SMALL size
- [x] Has a background image for the technology logo
- [x] Has name
- [x] Has description
- [x] Has years of experience
- [x] Has skill level
- [x] Has link to technology

Similar to this
![image](https://user-images.githubusercontent.com/5609118/49933139-cb235100-fec2-11e8-9eb4-e7aafcab7043.png)
