### ISSUE TITLE
Create dialog for ShowcaseItem onclick

### ISSUE THREAD

**Issue by hrafnkellbaldurs** [hrafnkellbaldurs/hrafnkellbaldurs-netlify#58]
Related to #14 
Needs #31 to be done to be able to start development

## TODO
- [x] Uses MEDIUM size
- [x] Has a background image for the screenshot
- [x] Has title
- [x] Has subtitle
- [x] Has description
- [x] Has tags
- [x] Has coAuthors
- [x] Create small function to determine button type
- [x] Has link to source code
- [x] Source code Link icon is based on url src containing 'github', 'codepen' or similar
- [x] If link is contained in play store, display play store button

Similar to this
![image](https://user-images.githubusercontent.com/5609118/49933139-cb235100-fec2-11e8-9eb4-e7aafcab7043.png)
