### ISSUE TITLE
Implement theme colors with scss across site

### ISSUE THREAD

**Issue by hrafnkellbaldurs** [hrafnkellbaldurs/hrafnkellbaldurs-netlify#7]
#### Nr .1
Possible color scheme: https://www.behance.net/gallery/70158287/Personal-Portfolio-Template-Design-Free-Download

Primary: #010312
Accent: #117bfb
Secondary: #f8f5f5

- [x] Nav
  - [x] bg = Primary
  - [x] border-bottom = 1px solid rgba(Secondary, 0.2)
  - [x] NavItem
    - [x] color = isCurrent ? Accent : Secondary
- [x] Hero
  - [x] bg overlay =  radial gradient showing highlight(Primary)
  - [x] color  = contrast bg
- [x] About me
  - [x] bg = Primary
  - [x] color = contrast-color('dark')
    - [x] Label 
      - [x] color = Accent
- [x] Resume, Portfolio
  - [x] bg = Secondary
    - [x] Title
      - [x] color = accent
- [x] Footer
  - [x] bg = Primary
  - [x] color = contrast-color('dark')

### TODO
- [x] Create map for theme-colors
  - [x] Define map
  - [x] Define function to access map
  - [x] Complete color scheme
- [x] Create map for contrast-colors
  - [x] Define map
  - [x] Define function to access map
  - [x] Define mixin for contrast-color
  - [x] Complete color scheme
- [x] Implement theme-color and contrast-color across webpage
  - [x] Header
  - [x] SocialLinks
  - [x] _default.scss
  - [x] _fonts.scss
  - [x] _layout.scss
  - [x] _media-queries.scss
  - [x] _svg.scss

**Comment by hrafnkellbaldurs** [comment]
Relevant changeset: e7b0ee192ab84f2cd9a59f7d4b8735da2bdc8bfc
